import { useState, type FormEvent } from "react";
import { errorMessage, useSession } from "../lib/session.js";
import { defaultDeviceName } from "../lib/device.js";

/**
 * Shown when the signed-in user has no shop, or this terminal isn't yet
 * bound to a shop (TRD §1 device activation).
 *
 * Two activation paths:
 *  - "Enter a code" — code generated elsewhere (web dashboard, Stage 8).
 *  - "Activate as owner" — the Owner is standing at this terminal, so we
 *    mint a code and redeem it in one step. Same DB path, no shortcut.
 */
export function SetupScreen() {
  const { ctx, auth, device, setDevice, refresh, signOut } = useSession();
  const memberships = ctx?.memberships ?? [];
  const canActivate = memberships.filter((m) => m.permissions.includes("shop.settings"));

  const [shopName, setShopName] = useState("");
  const [code, setCode] = useState("");
  const [deviceName, setDeviceName] = useState(defaultDeviceName());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function run(fn: () => Promise<void>) {
    setBusy(true);
    setError(null);
    try {
      await fn();
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setBusy(false);
    }
  }

  function createShop(e: FormEvent) {
    e.preventDefault();
    void run(async () => {
      await auth.createShop(shopName);
      await refresh();
    });
  }

  function activateWithCode(e: FormEvent) {
    e.preventDefault();
    void run(async () => {
      setDevice(await auth.activateDevice(code, deviceName));
    });
  }

  function activateAsOwner(shopId: string) {
    void run(async () => {
      const { code } = await auth.createActivationCode(shopId);
      setDevice(await auth.activateDevice(code, deviceName));
    });
  }

  const boundToOtherShop = device && !memberships.some((m) => m.shop.id === device.shop_id);

  return (
    <div className="min-h-full flex items-center justify-center p-6">
      <div className="w-full max-w-md space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-xl font-semibold">Set up this terminal</h1>
            <p className="text-sm text-muted-foreground">Signed in as {ctx?.user?.full_name}</p>
          </div>
          <button className="btn-ghost" onClick={() => void signOut()}>Sign out</button>
        </div>

        {error && <div className="alert-error">{error}</div>}

        {boundToOtherShop && (
          <div className="card space-y-2">
            <p className="text-sm">
              This terminal is activated for a shop you're not a member of. Ask that shop's owner to
              invite you, or reset the terminal.
            </p>
            <button className="btn-secondary" onClick={() => setDevice(null)}>Reset terminal binding</button>
          </div>
        )}

        {memberships.length === 0 && (
          <form onSubmit={createShop} className="card space-y-3">
            <h2 className="font-medium">Open a new shop</h2>
            <p className="text-sm text-muted-foreground">You'll be its Owner. Staff can be invited afterwards.</p>
            <div>
              <label className="label" htmlFor="shopName">Shop name</label>
              <input id="shopName" className="input" value={shopName} onChange={(e) => setShopName(e.target.value)} required minLength={1} maxLength={120} autoFocus />
            </div>
            <button className="btn-primary" disabled={busy}>Create shop</button>
          </form>
        )}

        {!device && memberships.length > 0 && (
          <>
            <div className="card space-y-3">
              <h2 className="font-medium">Terminal name</h2>
              <input className="input" value={deviceName} onChange={(e) => setDeviceName(e.target.value)} maxLength={80} />
            </div>

            {canActivate.length > 0 && (
              <div className="card space-y-3">
                <h2 className="font-medium">Activate for your shop</h2>
                {canActivate.map((m) => (
                  <button key={m.shop.id} className="btn-primary w-full" disabled={busy} onClick={() => activateAsOwner(m.shop.id)}>
                    Activate for “{m.shop.name}”
                  </button>
                ))}
              </div>
            )}

            <form onSubmit={activateWithCode} className="card space-y-3">
              <h2 className="font-medium">Or enter an activation code</h2>
              <p className="text-sm text-muted-foreground">Generated by the shop owner from the dashboard. Valid 10 minutes.</p>
              <input className="input font-mono tracking-widest uppercase" value={code} onChange={(e) => setCode(e.target.value)} placeholder="ABCD2345" maxLength={8} required />
              <button className="btn-secondary w-full" disabled={busy || code.length < 8}>Activate</button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}
